#version: "3.9"
#
#services:
#  backend:
#    build: backend
#    ports:
#      - "8000:8000"
#    volumes:
#      - ./backend:/app
#
#  frontend:
#    build: frontend
#    ports:
#      - "8501:8501"
#    depends_on:
#      - backend


version: "3.9"

services:
  backend:
    build: backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
